FROM registry.svc.ci.openshift.org/ocp/builder:rhel-8-base-openshift-4.8

RUN dnf upgrade -y \
 && dnf install -y qemu-img jq xz \
 && dnf clean all \
 && rm -rf /var/cache/{yum,dnf}/*

COPY ./get-resource.sh /usr/local/bin/get-resource.sh

